FROM debian:bookworm


RUN apt update && apt upgrade -y && apt install -y mariadb-server

RUN mkdir -p /etc/mysql

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/

RUN chmod 644 /etc/mysql/mariadb.conf.d/50-server.cnf

RUN mkdir -p /run/mysqld /var/lib/mysql /var/log/mysql && \
    chown -R mysql:mysql /run/mysqld /var/lib/mysql /var/log/mysql

COPY tools/mariadb-setup.sh .


RUN chmod +x ./mariadb-setup.sh

ENTRYPOINT [ "sh", "./mariadb-setup.sh" ]