version: "3.8"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yel-yaqi/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yel-yaqi/data/wordpress

services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    image: mariadb:mariadb_inception
    container_name: mariadb
    restart: always
    env_file: /home/debian/Desktop/secrets/.env
    networks:
      - inception
    expose:
      - 3306
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    image: wordpress:wordpress_inception
    container_name: wordpress
    restart: always
    env_file: /home/debian/Desktop/secrets/.env
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html

  nginx:
    build:
      context: ./srcs/requirements/nginx
    image: nginx:nginx_inception
    container_name: nginx
    restart: always
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
