FROM debian:bookworm

RUN apt update && apt upgrade -y \
    && apt install -y wget lsb-release ca-certificates apt-transport-https curl \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list \
    && apt update \
    && apt install -y php8.1-fpm php8.1-mysql php8.1-mysqli mariadb-client

RUN wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp

RUN mkdir -p /run/php /var/www/html \
    && chown www-data:www-data /run/php /var/www/html

COPY conf/www.conf /etc/php/8.1/fpm/pool.d/
COPY tools/setup-wp.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/setup-wp.sh

ENTRYPOINT ["sh", "/usr/local/bin/setup-wp.sh"]

EXPOSE 9000

CMD ["php-fpm8.1", "--nodaemonize"]
