FROM debian:bookworm

RUN apt update && apt upgrade -y && apt install -y nginx openssl gettext-base

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -subj "/C=MO/ST=KH/L=KH/O=1337/OU=1337/CN=aboulakr.42.fr/UID=aboulakr" \
    -keyout /etc/nginx/ssl/aboulakr.key \
    -out /etc/nginx/ssl/aboulakr.crt

COPY conf/nginx.conf ./temp/nginx.conf

RUN envsubst 'aboulakr.42.fr' < ./temp/nginx.conf > /etc/nginx/sites-available/default

ENTRYPOINT ["nginx", "-g", "daemon off;"]