FROM debian:bookworm

RUN apt update && apt upgrade -y && apt install -y nginx openssl

RUN mkdir -p /etc/nginx/ssl \
    && openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -subj "/C=MA/ST=KH/L=KH/O=42/OU=1337/CN=yel-yaqi.42.fr/UID=yel-yaqi" \
        -keyout /etc/nginx/ssl/yel-yaqi.key \
        -out /etc/nginx/ssl/yel-yaqi.crt

COPY conf/nginx.conf /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]
