FROM debian:bookworm

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y nginx openssl gettext-base \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl \
    && openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -subj "/C=MO/ST=KH/L=KH/O=1337/OU=1337/CN=yel-yaqi.42.fr/UID=yel-yaqi" \
        -keyout /etc/nginx/ssl/yel-yaqi.key \
        -out /etc/nginx/ssl/yel-yaqi.crt

COPY conf/nginx.conf /tmp/nginx.conf
RUN envsubst '${SERVER_NAME:-${DOMAIN_NAME}}' < /tmp/nginx.conf > /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]
